export const controllerTemplate = `// Auto-generated by zapit ⚡
import { Controller, Get, Post, Put, Delete, Param, Body, UsePipes } from '@nestjs/common';
import { {{name}}Service } from './{{kebabName}}.service';
import { Create{{name}}Dto, Update{{name}}Dto, {{name}}ResponseDto } from './dto/{{kebabName}}.dto';
import { ZodValidationPipe } from './validation.pipe';

@Controller('{{kebabName}}s')
export class {{name}}Controller {
  constructor(private readonly service: {{name}}Service) {}

  @Post()
  @UsePipes(new ZodValidationPipe(Create{{name}}Dto.schema))
  async create(@Body() dto: Create{{name}}Dto): Promise<{{name}}ResponseDto> {
    return this.service.create(dto);
  }

  @Get()
  async findAll(): Promise<{{name}}ResponseDto[]> {
    return this.service.findAll();
  }

  @Get(':id')
  async findOne(@Param('id') id: string): Promise<{{name}}ResponseDto> {
    return this.service.findOne(id);
  }

  @Put(':id')
  async update(
    @Param('id') id: string,
    @Body() dto: Update{{name}}Dto,
  ): Promise<{{name}}ResponseDto> {
    return this.service.update(id, dto);
  }

  @Delete(':id')
  async remove(@Param('id') id: string): Promise<void> {
    return this.service.remove(id);
  }
}
`;
