export const dtoTemplate = `// Auto-generated by zapit ⚡
// Do not edit manually — regenerate from your Zod schema

{{#each fields}}
{{#unless (eq name "id")}}
{{/unless}}
{{/each}}

export class Create{{name}}Dto {
{{#each fields}}
{{#unless (eq name "id")}}
  {{name}}{{#if optional}}?{{/if}}: {{tsType type}};
{{/unless}}
{{/each}}
}

export class Update{{name}}Dto {
{{#each fields}}
{{#unless (eq name "id")}}
  {{name}}?: {{tsType type}};
{{/unless}}
{{/each}}
}

export class {{name}}ResponseDto {
  id: string;
{{#each fields}}
{{#unless (eq name "id")}}
  {{name}}{{#if optional}}?{{/if}}: {{tsType type}};
{{/unless}}
{{/each}}
  createdAt: string;
  updatedAt: string;
}
`;
