export const moduleTemplate = `// Auto-generated by zapit ⚡
import { Module } from '@nestjs/common';
import { {{name}}Controller } from './{{kebabName}}.controller';
import { {{name}}Service } from './{{kebabName}}.service';
import { {{name}}Repository } from './{{kebabName}}.repository';

@Module({
  controllers: [{{name}}Controller],
  providers: [{{name}}Service, {{name}}Repository],
  exports: [{{name}}Service],
})
export class {{name}}Module {}
`;
