import { ParsedSchema } from '../parser';

const typeMap: Record<string, string> = {
  string: 'String',
  number: 'Int',
  boolean: 'Boolean',
  date: 'DateTime',
};

export function generatePrismaModel(schema: ParsedSchema): string {
  const lines: string[] = [];
  lines.push(`// Auto-generated by zapit ⚡`);
  lines.push(`// Add this to your prisma/schema.prisma`);
  lines.push(``);
  lines.push(`model ${schema.name} {`);
  lines.push(`  id        String   @id @default(uuid())`);

  for (const field of schema.fields) {
    if (field.name === 'id') continue;
    const prismaType = typeMap[field.type] || 'String';
    const opt = field.optional ? '?' : '';
    lines.push(`  ${field.name.padEnd(9)} ${prismaType}${opt}`);
  }

  lines.push(`  createdAt DateTime @default(now())`);
  lines.push(`  updatedAt DateTime @updatedAt`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}
