export const prismaRepositoryTemplate = `// Auto-generated by zapit ⚡
import { Injectable } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { Create{{name}}Dto, Update{{name}}Dto, {{name}}ResponseDto } from './dto/{{kebabName}}.dto';

@Injectable()
export class {{name}}Repository {
  private readonly prisma = new PrismaClient();

  async create(dto: Create{{name}}Dto): Promise<{{name}}ResponseDto> {
    return this.prisma.{{camelName}}.create({ data: dto }) as any;
  }

  async findAll(): Promise<{{name}}ResponseDto[]> {
    return this.prisma.{{camelName}}.findMany() as any;
  }

  async findOne(id: string): Promise<{{name}}ResponseDto | null> {
    return this.prisma.{{camelName}}.findUnique({ where: { id } }) as any;
  }

  async update(id: string, dto: Update{{name}}Dto): Promise<{{name}}ResponseDto> {
    return this.prisma.{{camelName}}.update({ where: { id }, data: dto }) as any;
  }

  async remove(id: string): Promise<void> {
    await this.prisma.{{camelName}}.delete({ where: { id } });
  }
}
`;
