export const repositoryTemplate = `// Auto-generated by zapit ⚡
import { Injectable } from '@nestjs/common';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  PutCommand,
  GetCommand,
  ScanCommand,
  UpdateCommand,
  DeleteCommand,
} from '@aws-sdk/lib-dynamodb';
import { randomUUID } from 'crypto';
import { Create{{name}}Dto, Update{{name}}Dto, {{name}}ResponseDto } from './dto/{{kebabName}}.dto';

@Injectable()
export class {{name}}Repository {
  private readonly tableName = '{{name}}s';
  private readonly docClient: DynamoDBDocumentClient;

  constructor() {
    const client = new DynamoDBClient({});
    this.docClient = DynamoDBDocumentClient.from(client);
  }

  async create(dto: Create{{name}}Dto): Promise<{{name}}ResponseDto> {
    const now = new Date().toISOString();
    const item = {
      id: randomUUID(),
      ...dto,
      createdAt: now,
      updatedAt: now,
    };

    await this.docClient.send(
      new PutCommand({ TableName: this.tableName, Item: item }),
    );

    return item as {{name}}ResponseDto;
  }

  async findAll(): Promise<{{name}}ResponseDto[]> {
    const result = await this.docClient.send(
      new ScanCommand({ TableName: this.tableName }),
    );
    return (result.Items || []) as {{name}}ResponseDto[];
  }

  async findOne(id: string): Promise<{{name}}ResponseDto | null> {
    const result = await this.docClient.send(
      new GetCommand({ TableName: this.tableName, Key: { id } }),
    );
    return (result.Item as {{name}}ResponseDto) || null;
  }

  async update(id: string, dto: Update{{name}}Dto): Promise<{{name}}ResponseDto> {
    const fields = Object.entries(dto).filter(([_, v]) => v !== undefined);
    const expressionParts: string[] = ['#updatedAt = :updatedAt'];
    const names: Record<string, string> = { '#updatedAt': 'updatedAt' };
    const values: Record<string, any> = { ':updatedAt': new Date().toISOString() };

    for (const [key, value] of fields) {
      expressionParts.push(\\\`#\\\${key} = :\\\${key}\\\`);
      names[\\\`#\\\${key}\\\`] = key;
      values[\\\`:\\\${key}\\\`] = value;
    }

    const result = await this.docClient.send(
      new UpdateCommand({
        TableName: this.tableName,
        Key: { id },
        UpdateExpression: \\\`SET \\\${expressionParts.join(', ')}\\\`,
        ExpressionAttributeNames: names,
        ExpressionAttributeValues: values,
        ReturnValues: 'ALL_NEW',
      }),
    );

    return result.Attributes as {{name}}ResponseDto;
  }

  async remove(id: string): Promise<void> {
    await this.docClient.send(
      new DeleteCommand({ TableName: this.tableName, Key: { id } }),
    );
  }
}
`;
