export const serviceTemplate = `// Auto-generated by zapit ⚡
import { Injectable, NotFoundException } from '@nestjs/common';
import { {{name}}Repository } from './{{kebabName}}.repository';
import { Create{{name}}Dto, Update{{name}}Dto, {{name}}ResponseDto } from './dto/{{kebabName}}.dto';

@Injectable()
export class {{name}}Service {
  constructor(private readonly repository: {{name}}Repository) {}

  async create(dto: Create{{name}}Dto): Promise<{{name}}ResponseDto> {
    return this.repository.create(dto);
  }

  async findAll(): Promise<{{name}}ResponseDto[]> {
    return this.repository.findAll();
  }

  async findOne(id: string): Promise<{{name}}ResponseDto> {
    const item = await this.repository.findOne(id);
    if (!item) {
      throw new NotFoundException(\\\`{{name}} with id \\\${id} not found\\\`);
    }
    return item;
  }

  async update(id: string, dto: Update{{name}}Dto): Promise<{{name}}ResponseDto> {
    await this.findOne(id); // ensure exists
    return this.repository.update(id, dto);
  }

  async remove(id: string): Promise<void> {
    await this.findOne(id); // ensure exists
    return this.repository.remove(id);
  }
}
`;
