export function initCdkApp(projectName: string): string {
  const pascalName = projectName
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
    .replace(/^./, c => c.toUpperCase());

  return `#!/usr/bin/env node
// Generated by zapit ⚡
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { ${pascalName}Stack } from './stack';

const app = new cdk.App();
new ${pascalName}Stack(app, '${pascalName}Stack');
`;
}
